### ISSUE TITLE
Small Changes To Text

### ISSUE THREAD

**Issue by ChockIZ** [KevinMarley/KevinMarley.github.io#8]
Under “Meet Kevin”

    • Should be “Ancaster High School” instead of just “Ancaster High”
    • Should have a period after “B.A”

Under “Ward 12 Priorities”

    • “people” in “people need more efficient ways…” should be “community members” or “members of the community”
    • The sentence “more roads going to high volume areas” should have a comma after “areas” and “traffic circles”
    • Take out “of the area” in “…traffic circles can the growing population of the area get around.”

In “Boundaries”

    • Outlying  surrounding?
    • “It” in the second paragraph is fully bolded, should just be the “I”
    • “…come to a consensus on what changes [are a priority for the ward]”?

In “City-Wide Concerns”

    • “In” is fully bolded again, should just be the “I”
    • “road quality has been an issue [in] Hamilton for a long time”
    • “the city should stay on top of [repairs]”?
    

    • “Public transit is [currently] a key issue for the city of Hamilton.”
    • Cut out “City transit drastically needs to be improved”
    • Add a semicolon after “forward for our city”  should read “…forward for our city; it should bring more foot traffic…”

    • In the “other initiatives” paragraph, should be “in order to provide access **to** academic journals **for** the public”

**Comment by greyscaled** [comment]
@ChockIZ  can you clarify:

Outlying  surrounding?

This shows up as a square circle for me, what is it intended to be?

**Comment by greyscaled** [comment]
Resolved in #9
